# Generated by Django 4.1.4 on 2022-12-26 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("countries", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="country",
            old_name="capltial",
            new_name="capital",
        ),
    ]
